fine-ants/frontend

__tests__/hooks/useFunnel.test.tsx, src/hooks/useFunnel.tsx, src/pages/SignUpPage/SignUpPage.tsx, src/pages/SignUpPage/subPages/EmailSubPage.tsx, src/pages/SignUpPage/subPages/MainSubPage.tsx, src/pages/SignUpPage/subPages/NicknameSubPage.tsx, src/pages/SignUpPage/subPages/PasswordSubPage.tsx, src/pages/SignUpPage/subPages/SubPage.tsx, src/pages/SignUpPage/subPages/VerificationSubPage.tsx
- useFunnel hook
- useFunnel hook test
=> [refactor] useFunnel hook 구현

src/api/auth/index.ts, src/components/Portfolio/Charts/HoldingsPieChart.tsx, src/components/hooks/useImageInput.tsx, src/pages/SignUpPage/SignUpPage.tsx, src/pages/SignUpPage/subPages/EmailSubPage.tsx, src/pages/SignUpPage/subPages/NicknameSubPage.tsx, src/pages/SignUpPage/subPages/PasswordSubPage.tsx, src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx, src/pages/SignUpPage/subPages/SubPage.tsx
=> [feat] 회원가입 이미지 입력 단계 추가

src/api/portfolio/queries/usePortfolioListQuery.ts, src/api/stock/index.ts, src/components/Portfolio/PortfolioHoldings/PortfolioHoldingAddDialog.tsx, src/components/SearchBar/SearchBar.tsx, src/components/Watchlist/WatchlistItemAddDialog.tsx, src/components/common/Header.tsx, src/components/hooks/useInputDebounce.ts, src/pages/SignInPage.tsx
- 검색바 debounce 적용 및 context 제거
- `SignInPage` useEffect 간소화
=> [refactor] 검색바 debounce 적용 및 context 제거

src/components/Portfolio/PortfolioList/errorFallback/PortfolioListTableErrorFallback.tsx, src/components/common/AsyncBoundary.tsx, src/mocks/handlers/portfolioHandlers.ts, src/pages/DashboardPage.tsx, src/pages/GlobalErrorPage.tsx, src/pages/NotFoundPage.tsx, src/pages/Portfolio/PortfolioListPage.tsx, src/router/router.tsx
- https://github.com/fine-ants/frontend/issues/51
Closes #51
=> [feat] PortfolioListPage 및 Root Level ErrorBoundary 적용

src/api/auth/index.ts, src/api/auth/queries/useOAuthSignInMutation.ts, src/components/auth/GoogleSignInButton.tsx, src/components/auth/KakaoSignInButton.tsx, src/components/auth/NaverSignInButton.tsx, src/pages/SignInLoadingPage.tsx, src/pages/SignInPage.tsx, src/router/Routes.ts, src/router/router.tsx
- OAuth PopUp Window 바로 닫힘 현상 해결
- `SignInLoadingPage`
- 기타 리팩토링
- #62 
Closes #62
=> [fix] OIDC Window Popup 바로 닫힘 현상 해결

src/pages/SignInPage.tsx
=> #62 refactor: shouldClosePopUp 로직 수정

src/components/Portfolio/PortfolioHoldings/PortfolioHoldingsTable.tsx, src/components/Portfolio/PortfolioList/PortfolioListTable.tsx, src/components/Watchlist/WatchlistTable.tsx, src/components/common/Pagination/TablePagination.tsx
- 해당 이슈 내용을 참고해주세요.
- #74 
Closes #74
=> [fix] TablePagination `rowsPerPageOptions`이 "All"일 때 sort 미적용 버그 해결

src/pages/SignInLoadingPage.tsx
- signinloadingpage ui 추가 했습니다.
- 회원가입, 로그인 이슈에서 `SignInPage` 디렉터리를 만들어 두어서 그 이슈에서 같은 폴더로 정리해 놓겠습니다.
=> signinloadingpage UI

src/components/Portfolio/Charts/ChartsPanel.tsx, src/components/Portfolio/MainPanel.tsx, src/components/Portfolio/PortfolioAddDialog.tsx, src/components/Portfolio/PortfolioOverview.tsx, src/pages/Portfolio/PortfolioPage.tsx, src/router/Routes.ts
=> [deploy] 배포

src/api/fetcher.ts
=> refresh token 만료시 error 무한 루프 해결

package-lock.json, package.json, public/mockServiceWorker.js, src/api/portfolio/types.ts, src/main.tsx, src/mocks/browserServiceWorker.ts, src/mocks/data/stockData.ts, src/mocks/data/watchlistData.ts, src/mocks/handlers/authHandlers.ts, src/mocks/handlers/dashboardHandlers.ts, src/mocks/handlers/index.ts, src/mocks/handlers/portfolioHandlers.ts, src/mocks/handlers/stockHandlers.ts, src/mocks/handlers/watchlistHandlers.ts, tsconfig.json, vite.config.ts
=> [migrate] MSW 2.1.1

src/components/common/toast/CustomToastContainer.tsx, src/components/common/toast/createToast.tsx
=> toast alert 가운데로 위치 변경

package-lock.json, package.json, public/mockServiceWorker.js, src/api/auth/index.ts, src/components/auth/SocialLoginButton.tsx, src/main.tsx, src/pages/SignUpPage/SignUpPage.tsx, src/pages/SignUpPage/subPages/EmailSubPage.tsx
- 회원가입 api 적용
- 회원가입 api 호출 MSW 문제 임시로 해결
=> 회원가입 api 적용

src/api/portfolio/queries/usePortfolioEditMutation.ts, src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx, src/components/Portfolio/PortfolioOverview.tsx, src/components/TradingViewWidgets/TVStockDetailWidget.tsx, src/components/Watchlist/WatchlistItemAddDialog.tsx, src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx, src/components/common/Buttons/Button.tsx, src/components/common/Header/Header.tsx, src/pages/IndicesPage.tsx, src/pages/StockPage.tsx, src/router/Routes.ts, src/router/router.tsx
=> [refactor] 자잘한 수정사항들 적용

src/api/fcm.ts, src/api/notifications/index.ts, src/components/common/Header/Notification/NotificationSettingsDialog.tsx, src/context/UserContext.tsx, src/mocks/data/notifications/notificationSettingsData.ts, src/mocks/handlers/notifications/notificationSettingsHandlers.ts, src/utils/retryFn.ts
- https://github.com/fine-ants/frontend/issues/132
Closes #132
=> [feat] FCM 토큰 삭제 기능

src/api/notifications/index.ts, src/api/notifications/queries/queryKeys.ts, src/api/notifications/queries/useSpecificStockTargetPricesQuery.ts, src/api/notifications/queries/useStockTargetPriceDeleteMutation.ts, src/components/Stock/TargetPriceAlertDropdown/TargetPriceAlertDropdown.tsx, src/components/Stock/TargetPriceAlertDropdown/TargetPricesList.tsx, src/components/Stock/TargetPriceAlertDropdown/errorFallback/TargetPricesListErrorFallback.tsx, src/components/Stock/TargetPriceAlertDropdown/skeleton/TargetPricesListSkeleton.tsx, src/mocks/data/notifications/notificationSettingsData.ts, src/mocks/handlers/notifications/notificationSettingsHandlers.ts, src/pages/StockPage.tsx
- https://github.com/fine-ants/frontend/issues/134
Closes #134
=> [feat] 종목 페이지 추가된 알림 Dropdown 구현

src/api/fcm.ts, src/api/notifications/types.ts, src/components/common/Header/Notification/EmptyNotification.tsx, src/components/common/Header/Notification/NotificationItem.tsx, src/mocks/data/notifications/memberNotificationsData.ts
- Foreground 알림 추가
- NotificationPanel "알림이 없습니다" 문구 색상 변경
- NotificationPanel item body bold 처리
=> 알림 관련 리팩터링

README.md, src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx, src/mocks/data/notifications/notificationSettingsData.ts
- PortfolioHoldingsTable row expand할 시에 1px scroll 생기는 버그
Closes #138
=> [fix] PortfolioHoldingsTable 1px scroll 버그

src/api/portfolio/index.ts, src/api/portfolio/types.ts, src/components/Portfolio/Charts/ChartsPanel.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx, src/mocks/data/portfolioData.ts, src/mocks/handlers/portfolioHandlers.ts, src/utils/executeIfNumeric.ts
- MSW 서버와 비슷하게 수정
- 예상 월 배당금 막대그래프 호버시 tooltip 2024-NaN 해결
- 섹터 구성 합계가 100%가 아닌 부분 해결
- 포트폴리오 상세 페이지 우측 구성 border-radius 없음
- 포트폴리오 상세 페이지 "종목 추가 모달"에서 purchaseHistory 항목이 누락된 채로 요청이 됨
=> [refactor] portfolio page 리팩터링

src/hooks/useNicknameDuplicateCheck.tsx, src/pages/AuthBasePage.tsx, src/pages/SignUpPage/SignUpPage.tsx, src/pages/SignUpPage/subPages/EmailSubPage.tsx, src/pages/SignUpPage/subPages/NicknameSubPage.tsx, src/pages/SignUpPage/subPages/PasswordSubPage.tsx, src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx, src/pages/SignUpPage/subPages/VerificationSubPage.tsx
- https://github.com/fine-ants/frontend/issues/143
=> [fix] Signup Page 닉네임 및 프로필 사진

src/api/fetcher.ts, src/api/user/index.ts, src/api/user/queries/useProfileDetailsMutation.ts, src/mocks/data/userData.ts, src/mocks/handlers/userHandlers.ts, src/pages/ProfilePage/subPages/ProfileSettingsSubPage.tsx, src/pages/SignUpPage/SignUpPage.tsx, src/pages/SignUpPage/subPages/ProfileImageSubPage.tsx
- https://github.com/fine-ants/frontend/issues/148
=> [fix/refactor] Profile Settings Page

src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx, src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx, src/components/SearchBar/SearchBar.tsx, src/components/Watchlist/NewWatchlistDialog.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableToolBar.tsx, src/components/Watchlist/WatchlistsTable/WatchlistsTableToolBar.tsx, src/components/common/DatePicker/DatePicker.tsx, src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownListSkeleton.tsx, src/components/common/Spinner.tsx, src/components/common/Table/CollapsibleSelectableTable.tsx, src/components/common/Table/SelectableTable.tsx, src/pages/SignInPage/SignInLoadingPage.tsx
- https://github.com/fine-ants/frontend/issues/155
=> [fix/refactor] 행 삭제 후 TableHead checkbox 선택되는 현상 및 기타 UI 수정

src/components/Portfolio/PortfolioOverview.tsx, src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx, src/components/common/DatePicker/DatePicker.tsx, src/pages/Portfolio/PortfolioPage.tsx, src/pages/Watchlist/WatchlistsPage.tsx
=> [fix] UI fixes

src/components/Dashboard/DashboardOverview.tsx, src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx, src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx
- https://github.com/fine-ants/frontend/issues/178
=> [fix] Remove unnecessary nullish coalescing operators

src/api/fcm.ts, src/firebase-messaging-sw.js
- https://github.com/fine-ants/frontend/issues/175
=> [fix] App이 Background에 있을 시 같은 알림이 두번 발생하는 현상

src/api/notifications/queries/useStockTargetPriceAddMutation.tsx, src/components/Dashboard/DashboardPortfolioWeight.tsx, src/components/Portfolio/PortfolioAddOrEditDialog.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotAddRow.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx, src/components/Portfolio/PortfolioList/EmptyPortfolioListTable.tsx, src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx, src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx, src/components/Stock/StockTargetPriceForm.tsx, src/components/common/Header/PortfoliosDropdown/PortfoliosDropdown.tsx, src/mocks/handlers/portfolioHandlers.ts, src/utils/calculations.ts, src/utils/excludeDelimiters.ts, src/utils/executeIfNumeric.ts
- https://github.com/fine-ants/frontend/issues/182
=> [feat] 종목 지정가 최대 5개 초과 등록 시도 시 토스트 발생 및 숫자 input 쉼표 적용

.gitignore, config/vitePlugins.ts, package-lock.json, package.json, src/firebase-messaging-sw.js, src/main.tsx, vite.config.ts
- https://github.com/fine-ants/frontend/issues/187
=> [refactor] 개발 모드 시 FCM Service Worker 미작동 문제 해결

config/vitePlugins.ts, src/main.tsx
- https://github.com/fine-ants/frontend/issues/193
=> [refactor] Read FCM SW file using node instead of rollup in fcmSwEnvPlugin

src/components/Portfolio/PortfolioAddOrEditDialog.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx, src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx, src/components/Watchlist/NewWatchlistDialog.tsx, src/components/Watchlist/WatchlistItemAddDialog.tsx, src/components/Watchlist/WatchlistNameEditDialog.tsx, src/components/common/Buttons/IconButton.tsx, src/components/common/Icon.tsx, src/components/common/Pagination/TablePagination.tsx
- https://github.com/fine-ants/frontend/issues/197
=> [refactor] Use form tags to allow enter for submissions

src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx, src/components/Watchlist/WatchlistItemAddDialog.tsx, src/components/common/Buttons/AsyncButton.tsx, src/components/common/Buttons/Button.tsx
- https://github.com/fine-ants/frontend/issues/200
=> [feat] AsyncButton 구현 및 적용

src/components/Portfolio/PortfolioHolding/PortfolioHoldingAddDialog.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx, src/components/SearchBar/SearchBar.tsx, src/components/common/Buttons/IconButton.tsx
- https://github.com/fine-ants/frontend/issues/205
=> [refactor] Search Autocomplete Enter 누르면 선택 또는 이동이 되도록 수정

src/components/Dashboard/PortfolioWeightPieChart/PortfolioWeightPieChartToolTip.tsx, src/components/Notification/StockNotificationList/StockNotificationLotsTable/StockNotificationLotRow.tsx, src/components/Notification/StockNotificationList/StockNotificationRow.tsx, src/components/Portfolio/PortfolioAddOrEditDialog.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingRow.tsx, src/components/Portfolio/PortfolioList/PortfolioListTableRow.tsx, src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx, src/components/Stock/TargetPriceAlertDropdown/TargetPricesList.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableToolBar.tsx, src/components/common/Header/Notification/NotificationPanel.tsx, src/components/common/RealtimeValue.tsx
- https://github.com/fine-ants/frontend/issues/208
=> [refactor] Table에서 ₩ 제거

src/api/user/types.ts, src/components/auth/SocialLoginButton.tsx, src/pages/ProfilePage/ProfilePage.tsx
- https://github.com/fine-ants/frontend/issues/212
=> [refactor] 이메일/비밀번호 계정일 때만 "계정 설정" 탭 활성화 

src/components/NavBar.tsx, src/components/SearchBar/RenderOptionDefault.tsx, src/components/SearchBar/SearchBar.tsx, src/components/common/Header/Notification/NotificationSettingsDialog.tsx, src/components/common/Header/PortfoliosDropdown/PortfoliosDropdown.tsx, src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownList.tsx, src/components/common/Header/PortfoliosDropdown/PortfoliosDropdownListSkeleton.tsx, src/components/common/Header/UserDropdown.tsx, src/components/hooks/useDropdown.tsx
- #211 
- 새탭으로 열기 안되는 부분 추가 작업
- `Watchlists`, `Indices`, `SearchBar 검색 결과`, `UserDropdown`, `PortfoliosDropdown`
=> [refactor] Header 리팩터링

src/components/Stock/StockTargetPriceForm.tsx, src/components/auth/SocialLoginButton.tsx, src/components/common/CustomTooltip.tsx, src/context/UserContext.tsx, src/pages/SignInPage/SignInForm.tsx
- https://github.com/fine-ants/frontend/issues/218
=> [feat] 최근 로그인한 방식 툴팁

index.html, src/components/Dashboard/PortfolioWeightPieChart/EmptyPortfolioMessage.tsx, src/components/Portfolio/Charts/Pie/EmptyHoldingsPieChartImg.tsx, src/components/Portfolio/PortfolioAddOrEditDialog.tsx, src/components/Portfolio/PortfolioHolding/EmptyPortfolioHoldingTable.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx, src/components/Portfolio/PortfolioList/EmptyPortfolioListTable.tsx, src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx, src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx, src/components/Stock/StockTargetPriceForm.tsx, src/components/Stock/TargetPriceAlertDropdown/TargetPriceAlertDropdown.tsx, src/components/Stock/WatchlistHasStock/WatchlistHasStockDropdown.tsx, src/components/Watchlist/NewWatchlistDialog.tsx, src/components/Watchlist/WatchlistNameEditDialog.tsx, src/components/Watchlist/WatchlistTable/EmptyWatchlistTable.tsx, src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableToolBar.tsx, src/components/Watchlist/WatchlistsTable/EmptyWatchlistsTable.tsx, src/components/Watchlist/WatchlistsTable/WatchlistsTableToolBar.tsx, src/components/common/Breadcrumb.tsx, src/components/common/Buttons/Button.tsx, src/components/common/Header/Notification/NotificationSettingsDialog.tsx, src/components/common/Pagination/Pagination.tsx, src/components/common/Select/Select.tsx, src/pages/SignInPage/SignInForm.tsx
=> [refactor] button component 및 기타 리팩터링

src/api/portfolio/queries/usePortfolioAddMutation.ts, src/api/portfolio/queries/usePortfolioEditMutation.ts, src/components/ConfirmAlert.tsx, src/components/Notification/PortfolioNotificationList/PortfolioNotificationRow.tsx, src/components/Portfolio/PortfolioAddOrEditDialog.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx, src/components/Portfolio/PortfolioHolding/PortfolioHoldingTableToolBar.tsx, src/components/Portfolio/PortfolioList/PortfolioListTableToolBar.tsx, src/components/Portfolio/PortfolioOverview/PortfolioOverview.tsx, src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx, src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableToolBar.tsx, src/components/Watchlist/WatchlistsTable/WatchlistsTableToolBar.tsx
- https://github.com/fine-ants/frontend/issues/221
=> [refactor] Dialog 문구 수정 및 포트폴리오 추가/수정 dialog 요청 조건 수정

src/components/Watchlist/WatchlistTable/WatchlistContainer.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableBody.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableHead.tsx, src/components/Watchlist/WatchlistTable/WatchlistTableRow.tsx
=> [refactor] Watchlist 디자인 수정

src/pages/ProfilePage/ProfilePage.tsx, src/pages/ProfilePage/subPages/AccountSettingsSubPage.tsx
- https://github.com/fine-ants/frontend/issues/227
=> [refactor] OAuth 로그인일 때 계정 삭제 옵션 제공

src/components/Portfolio/PortfolioAddOrEditDialog.tsx, src/components/Portfolio/PortfolioOverview/PortfolioOverviewBody.tsx, src/components/common/toast/CustomToastContainer.tsx, src/pages/Portfolio/PortfolioPage.tsx
- https://github.com/fine-ants/frontend/issues/229
=> [fix] PortfolioAddOrEditDialog 목표 수익률, 최대 손실율 input 계산 문제

src/api/notifications/types.ts, src/components/Notification/PortfolioNotificationList/PortfolioNotificationListTable.tsx
- https://github.com/fine-ants/frontend/issues/234
=> #234 refactor: 포트폴리오 활성 알림 목록 정렬 순서 기준 lastUpdated -> createdAt으로 변경

src/hooks/useResponsiveLayout.ts
- https://github.com/fine-ants/frontend/issues/240
=> [feat] useResponsiveLayout Hook

src/components/Buttons/IconButton.tsx, src/components/SearchBar/SearchBar.tsx, src/components/Select/Select.tsx, src/components/Table/CollapsibleSelectableTable.tsx, src/components/Table/CollapsibleTable.tsx, src/components/TextField/PasswordTextField.tsx, src/components/TextField/TextField.tsx, src/features/auth/components/SocialLoginButton.tsx, src/features/dashboard/components/DashboardPortfolioWeight.tsx, src/features/notification/components/FeedbackCallout.tsx, src/features/notification/components/NotificationPanel/NotificationItem.tsx, src/features/notification/components/StockNotificationList/StockNotificationLotsTable/StockNotificationLotRow.tsx, src/features/notification/components/StockNotificationList/StockNotificationRow.tsx, src/features/portfolio/components/PortfolioHolding/EmptyPortfolioHoldingTable.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableToolBar.tsx, src/features/portfolio/components/PortfolioList/EmptyPortfolioListTable.tsx, src/features/portfolio/components/PortfolioList/PortfolioListTableToolBar.tsx, src/features/portfolio/components/PortfolioOverview/PortfolioOverview.tsx, src/features/portfolio/components/PortfoliosDropdown/PortfoliosDropdown.tsx, src/features/stock/components/WatchlistHasStock/WatchlistHasStockDropdown.tsx, src/features/watchlist/components/WatchlistTable/EmptyWatchlistTable.tsx, src/features/watchlist/components/WatchlistTable/WatchlistContainer.tsx, src/features/watchlist/components/WatchlistTable/WatchlistTableToolBar.tsx, src/features/watchlist/components/WatchlistsTable/EmptyWatchlistsTable.tsx, src/features/watchlist/components/WatchlistsTable/WatchlistsTableToolBar.tsx, src/hooks/useBoolean.ts, src/hooks/useNicknameDuplicateCheck.ts, src/pages/profile/subPages/AccountSettingsSubPage.tsx
=> [refactor] useBoolean 적용

src/components/Badges/RateBadge.tsx, src/features/auth/api/queries/useSignUpMutation.ts, src/features/notification/components/EmptyNotificationList.tsx, src/features/portfolio/api/index.ts, src/features/portfolio/api/queries/usePortfolioHoldingAddMutation.ts, src/features/portfolio/api/queries/usePortfolioHoldingPurchaseEditMutation.ts, src/features/portfolio/api/types.ts, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotRow.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingLots/PortfolioHoldingLotsTable.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTable.tsx, src/features/portfolio/hooks/useSSE.ts, src/features/stock/components/StockDetails.tsx, src/features/watchlist/components/WatchlistItemAddDialog.tsx, src/mocks/data/notifications/memberNotificationsData.ts, src/mocks/handlers/notifications/memberNotificationsHandlers.ts, src/mocks/handlers/portfolioHandlers.ts
- https://github.com/fine-ants/frontend/issues/274
=> [refactor] Todo 주석 정리 및 처리

src/components/Toast/CustomToastContainer.tsx, src/features/dashboard/components/DashboardPortfolioWeight.tsx, src/features/notification/components/EmptyNotificationList.tsx, src/features/notification/components/NotificationPanel/NotificationItem.tsx
=> [refactor] 디자인 리팩터링

src/features/dashboard/components/DashboardPortfolioWeight.tsx, src/features/portfolio/components/PortfolioAddOrEditDialog/PortfolioAddOrEditDialog.tsx, src/features/portfolio/components/PortfolioAddOrEditDialog/hooks/usePortfolioAddOrEditDialogInputs.ts, src/features/portfolio/components/PortfolioList/EmptyPortfolioListTable.tsx, src/features/portfolio/components/PortfolioList/PortfolioListTableToolBar.tsx, src/features/portfolio/components/PortfolioOverview/PortfolioOverview.tsx, src/features/portfolio/components/PortfoliosDropdown/PortfoliosDropdown.tsx
- https://github.com/fine-ants/frontend/issues/284
=> [refactor] PortfolioAddOrEditDialog 훅 분리

src/features/notification/api/index.ts, src/features/notification/components/StockNotificationList/desktop/StockNotificationRow.tsx, src/features/notification/components/StockNotificationList/mobile/StockNotificationCardBody.tsx
=> [refactor] 종목 알림 전체삭제 안되는 문제 해결

src/components/SearchBar/RenderOptionDefault.tsx, src/components/SearchBar/desktop/SearchBarD.tsx, src/components/SearchBar/mobile/SearchBarM.tsx, src/features/watchlist/components/WatchlistItemAddDialog.tsx
- https://github.com/fine-ants/frontend/issues/293
=> [refactor] SearchBar Dropdown Enter to Navigate

src/components/NavBar/NavBar.tsx, src/components/PullToRefresh.tsx, src/constants/styleConstants.ts, src/features/notification/components/NotificationSettingsDialog/NotificationDeniedSign.tsx, src/features/notification/components/NotificationSettingsDialog/NotificationPWANotice.tsx, src/features/notification/components/NotificationSettingsDialog/NotificationSettingsContent.tsx, src/hooks/useDevice.ts, src/pages/BasePage.tsx
=> [refactor] UI 리팩터링

index.html, src/components/NavBar/NavBar.tsx, src/components/TextField/PasswordTextField.tsx, src/components/TextField/TextField.tsx, src/features/auth/components/SignInForm.tsx, src/pages/auth/signup/subPages/EmailSubPage.tsx
- #321
- meta tag maximum-scale 추가
=> [refactor] IOS PWA UI 및 기타 리팩터링

src/components/Badges/RateBadge.tsx, src/components/Table/CollapsibleSelectableTable.tsx, src/components/Table/CollapsibleTable.tsx, src/components/Table/PlainTable.tsx, src/components/Table/SelectableTable.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingRow.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingTableToolBar.tsx, src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableHead.tsx, src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableRow.tsx, src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableToolBar.tsx, src/features/watchlist/components/WatchlistTable/WatchlistTableToolBar.tsx, src/features/watchlist/components/WatchlistsTable/WatchlistsTableToolBar.tsx, src/mocks/data/portfolioData.ts, src/mocks/handlers/portfolioHandlers.ts
- https://github.com/fine-ants/frontend/issues/325
=> [bug] 기타 UI 버그 해결

package-lock.json, package.json, src/components/BaseDialog.tsx, src/components/Drawer/BottomDrawer.tsx, src/components/Drawer/RightDrawer.tsx, src/components/SelectDrawer/SelectDrawer.tsx, src/features/notification/components/NotificationSettingsDialog/mobile/NotificationSettingsDialogM.tsx, src/features/portfolio/components/PortfolioAddOrEditDialog/mobile/PortfolioAddOrEditDialogM.tsx, src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingAddDialogM.tsx, src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingSearchDrawerM.tsx, src/features/stock/components/mobile/TargetPriceAlertDialog.tsx, src/features/watchlist/components/dialog/mobile/NewWatchlistDialogM.tsx, src/features/watchlist/components/dialog/mobile/WatchlistItemAddDialogM.tsx, src/features/watchlist/components/dialog/mobile/WatchlistItemAddDrawerM.tsx, src/features/watchlist/components/dialog/mobile/WatchlistNameEditDialogM.tsx, src/hooks/useZIndex.ts
=> [refactor] z-index 리팩터링

src/components/Drawer/DrawerItem.tsx, src/features/notification/components/NotificationPanel/mobile/NotificationPanelDrawerM.tsx, src/features/portfolio/components/Portfolio/mobile/PortfolioActionDrawer.tsx, src/features/stock/components/mobile/StockActionDrawer.tsx, src/features/user/components/mobile/UserDrawer.tsx, src/features/watchlist/components/WatchlistTable/mobile/WatchlistActionDrawer.tsx, src/hooks/useZIndex.ts
- https://github.com/fine-ants/frontend/issues/340
=> [refactor] BottomDrawer의 DrawerItem 공통 컴포넌트

src/components/BaseDialog.tsx, src/components/ConfirmAlert.tsx, src/features/notification/components/StockNotificationList/StockNotificationDeleteAllConfirm.tsx, src/features/notification/components/StockNotificationList/StockNotificationDeleteConfirm.tsx, src/features/notification/components/StockNotificationList/desktop/StockNotificationLotsTable/StockNotificationLotRow.tsx, src/features/notification/components/StockNotificationList/desktop/StockNotificationRow.tsx, src/features/notification/components/StockNotificationList/mobile/StockNotificationCardBody.tsx, src/features/notification/components/StockNotificationList/mobile/StockNotificationTargetPrices.tsx, src/features/portfolio/components/Portfolio/mobile/PortfolioActionDrawer.tsx, src/features/portfolio/components/PortfolioDeleteConfirm.tsx, src/features/portfolio/components/PortfolioHolding/PortfolioHoldingSelectedDeleteConfirm.tsx, src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingLots/PortfolioHoldingLotRowD.tsx, src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingTableToolBar.tsx, src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingCardTableToolbar.tsx, src/features/portfolio/components/PortfolioHolding/mobile/PortfolioHoldingLots/PortfolioHoldingLotsCard.tsx, src/features/portfolio/components/PortfolioList/desktop/PortfolioListTableToolBar.tsx, src/features/portfolio/components/PortfolioOverview/desktop/PortfolioOverviewD.tsx, src/features/user/components/AccountDeleteDialog.tsx
=> [refactor] Confirmalert 리팩터링

src/components/ConfirmAlert.tsx, src/constants/isPageDepthOne.ts
=> [refactor: 리뷰 반영 및 isPageDepthOne 수정

src/features/notification/components/EmptyNotificationList.tsx, src/hooks/useZIndex.ts, src/pages/auth/SignInPage.tsx, src/pages/notifications/subPages/PortfolioNotificationsSubPage.tsx
=> Refactor/#353  UI refactoring

src/components/TradingViewWidgets/TVIndicesWidget.tsx, src/pages/IndicesPage.tsx, src/pages/NotFoundPage.tsx
=> [refactor] 인덱스 페이지 반응형 적용

src/components/Table/TableSkeleton.tsx, src/features/portfolio/components/PortfolioList/PortfolioList.tsx, src/features/watchlist/components/WatchlistsTable/Watchlists.tsx, src/pages/PortfolioListPage.tsx, src/pages/WatchlistsPage.tsx
=> [refactor] 리스트 페이지 스켈레톤 수정

src/components/Legend/WideLegendItem.tsx, src/components/Tooltips/EllipsisTextTooltip.tsx, src/features/portfolio/components/PortfolioHolding/desktop/PortfolioHoldingRow.tsx, src/pages/PortfolioPage.tsx
- #359 
- 포트폴리오 페이지 WideLegend, HoldingRow에 줄바꿈 될 수 있는 부분에 EllipsisTextTooltip 적용
=> [refactor] 포트폴리오 페이지 리팩터링
